# Generated by Django 6.1.1 on 2026-09-26 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('approve', 'Approve'), ('reject', 'Reject'), ('view', 'View'), ('other', 'Other')], db_index=True, max_length=10)),
                ('model_name', models.CharField(max_length=60)),
                ('object_id', models.CharField(blank=True, max_length=30)),
                ('remark', models.CharField(blank=True, max_length=250)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='core_activi_user_id_81b1f1_idx')],
            },
        ),
    ]
