# Generated by Django 6.1.1 on 2026-09-26 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenancePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt_no', models.CharField(blank=True, max_length=50)),
                ('mode', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('cheque', 'Cheque'), ('netbanking', 'Net Banking'), ('card', 'Card'), ('other', 'Other')], default='cash', max_length=15)),
                ('remark', models.CharField(blank=True, max_length=250)),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='payments/proofs/')),
                ('period_month', models.PositiveSmallIntegerField(default=1, help_text='Month (1-12) this payment is for')),
                ('period_year', models.PositiveSmallIntegerField(default=2026, help_text='Year this payment is for')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=250)),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft-delete flag; never hard-delete.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_approved', to=settings.AUTH_USER_MODEL)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='flats.flat')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Maintenance payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submit', 'Submitted'), ('approve', 'Approved'), ('reject', 'Rejected'), ('edit', 'Edited'), ('delete', 'Deleted')], max_length=10)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=250)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='payments.maintenancepayment')),
            ],
            options={
                'verbose_name_plural': 'Payment audit logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='maintenancepayment',
            index=models.Index(fields=['flat', 'status'], name='payments_ma_flat_id_0b3040_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancepayment',
            index=models.Index(fields=['status', 'created_at'], name='payments_ma_status_a131f2_idx'),
        ),
    ]
