# Generated by Django 6.1.1 on 2026-09-26 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('monthly_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Wing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_no', models.CharField(max_length=20)),
                ('floor', models.PositiveSmallIntegerField(default=1)),
                ('area_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('owner_name', models.CharField(max_length=100)),
                ('is_tenant_occupied', models.BooleanField(default=False, help_text='True if occupied by tenant, else owner')),
                ('monthly_maintenance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, limit_choices_to={'role': 'resident'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_flats', to=settings.AUTH_USER_MODEL)),
                ('wing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flats', to='flats.wing')),
            ],
            options={
                'ordering': ['wing__name', 'floor', 'flat_no'],
            },
        ),
        migrations.CreateModel(
            name='FlatServiceAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('enable', 'Enable'), ('disable', 'Disable'), ('create', 'Create'), ('update', 'Update')], max_length=10)),
                ('remark', models.CharField(blank=True, max_length=250)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_audit_logs', to='flats.flat')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='flats.service')),
            ],
            options={
                'verbose_name_plural': 'Flat service audit logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FlatService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], db_index=True, default='enabled', max_length=10)),
                ('remark', models.CharField(blank=True, max_length=250)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_changes', to=settings.AUTH_USER_MODEL)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='flats.flat')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flat_links', to='flats.service')),
            ],
            options={
                'verbose_name_plural': 'Flat services',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['flat', 'status'], name='flats_flats_flat_id_9bb1c9_idx')],
                'unique_together': {('flat', 'service')},
            },
        ),
        migrations.AddIndex(
            model_name='flat',
            index=models.Index(fields=['is_active'], name='flats_flat_is_acti_c48e84_idx'),
        ),
        migrations.AddIndex(
            model_name='flat',
            index=models.Index(fields=['created_at'], name='flats_flat_created_6e898b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='flat',
            unique_together={('wing', 'flat_no')},
        ),
    ]
