# Generated by Django 6.1.1 on 2026-09-26 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_links', to='flats.flat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flat_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Flat owners',
                'ordering': ['-is_primary', 'added_at'],
                'unique_together': {('flat', 'user')},
            },
        ),
    ]
