# Generated by Django 6.1.1 on 2026-09-26 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0002_flatowner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_owner_name', models.CharField(blank=True, max_length=100)),
                ('new_owner_name', models.CharField(max_length=100)),
                ('reason', models.CharField(blank=True, help_text='e.g. Sale deed, transfer, gift', max_length=250)),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_changes_logged', to=settings.AUTH_USER_MODEL)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_history', to='flats.flat')),
                ('new_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_changes_after', to=settings.AUTH_USER_MODEL)),
                ('previous_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_changes_before', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Owner change history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('id_proof_type', models.CharField(blank=True, help_text='Aadhaar / Passport / DL etc.', max_length=30)),
                ('id_proof_no', models.CharField(blank=True, max_length=40)),
                ('move_in_date', models.DateField()),
                ('move_out_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('vacated', 'Vacated')], db_index=True, default='active', max_length=10)),
                ('remark', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants_added', to=settings.AUTH_USER_MODEL)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenants', to='flats.flat')),
            ],
            options={
                'ordering': ['-move_in_date', '-created_at'],
                'indexes': [models.Index(fields=['flat', 'status'], name='flats_tenan_flat_id_fbf185_idx')],
            },
        ),
    ]
